### PR TITLE
Fix a bunch of bullshit things

### PR DESCRIPTION
**Pull request by Vortex2Oblivion**
- Uses latest libraries now.
- Stop shadowing classes.
- Replace flash imports with openfl ones.
- Remove smokey's atlas player and just use flxanimate (why the fuck wasnt this already a thing)
- Replace that stupid ass event system with an array (im gonna kill whoever wrote that)
- Use hxgamejolt-api instead of tentools
- Remove deprecated functions and vars
- Added pretty error message reporting in project.xml

### CODE REVIEW

**Comment by glowsoony** [comment]
Hey! I see that you are willing to help out sorting thing's I haven't gotten to do! thanks for the help! though the code is a bit outdated compared to the massive new code planned for this engine (I have all the changes, but haven't posted them to this site), I will keep this PR in mind but overall we decided up until now that we might use a custom flixel-lib (finally) for own uses to the engine, cause overriding over and over again seems to exhaust me a lot, so thanks for helping! I plan on already doing some of this stuff, so if you could (sorry for asking) sperate the changes of removing things with the changes of the events being an array? that would be appreciated! (but later because the charting state was majorly changed to have haxeui to include the ui like vanilla fnf.) If not ill go ahead and do it, either way thanks a lot!

**Comment by Vortex2Oblivion** [comment]
> we might use a custom flixel-lib (finally) for own uses to the engine, cause overriding over and over again seems to exhaust me a lot

Or you could just extend the classes rather than shadow them so you could still get flixel updates?

**Comment by glowsoony** [comment]
I still would go with the customer lib because I would rather be able to edit it and add things of own self use for the engine, which is something wanted instead of leaving them in the engine itself, not because of the updates.

**Comment by glowsoony** [comment]
Almost all of these things are finally up in experimental, once experimental is complete I will marge with main and so on, thanks for the hxgamejolt-api. (Check README.md in experimental)

**Comment by Vortex2Oblivion** [comment]
Your 14 different event values being different strings and not an array  are all still there 😭

**Comment by glowsoony** [comment]
I'm preparing for the next major update v1.6 which includes major changes including the fact the EventNote is a separate sprite from being instead a typedef and yes all 14 values are arrays (all changes until merged with main can be seen in experimental) taking bit by bit the FNF Vanilla items from prototype v0.3.3 and implementing them while changing some things here and there and there are no more 14 values unless it's the chart editor cause manually you have to edit them one by one but they are in one single array.

**Pull request closed without merging**
